# Generated by Django 5.0.2 on 2024-03-04 18:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_product_is_sale_product_sale_price_alter_order_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 3, 4, 21, 38, 50, 900785)),
        ),
    ]
